const fakeData = {
  map: "ferocity",
  id: "601d52137e9f54f8aa94431b",
  "original-ongoing-match-id": "bN0Fj4VHiM",
  durationInSeconds: 0,
  startTime: "2021-02-05T14:11:12.381+00:00",
  endTime: "0001-01-01T00:00:00+00:00",
  gameMode: 4,
  teams: [
    {
      players: [
        {
          race: 0,
          rndRace: null,
          oldMmr: 2253,
          currentMmr: 0,
          battleTag: "HuyaYumiko#4873",
          name: "HuyaYumiko",
          mmrGain: -2253,
          won: false,
          location: "AT",
          countryCode: "CN",
          country: null,
          twitch: "",
        },
        {
          race: 0,
          rndRace: null,
          oldMmr: 2197,
          currentMmr: 0,
          battleTag: "RTGOD#2220",
          name: "RTGOD",
          mmrGain: -2197,
          won: false,
          location: "DE",
          countryCode: "DE",
          country: null,
          twitch: "weakudwc3",
        },
        {
          race: 8,
          rndRace: null,
          oldMmr: 1776,
          currentMmr: 0,
          battleTag: "Mendi#21932",
          name: "Mendi",
          mmrGain: -1776,
          won: false,
          location: "SI",
          countryCode: "JM",
          country: null,
          twitch: "",
        },
        {
          race: 1,
          rndRace: null,
          oldMmr: 1767,
          currentMmr: 0,
          battleTag: "ChefKAYDI#2946",
          name: "ChefKAYDI",
          mmrGain: -1767,
          won: false,
          location: "FR",
          countryCode: null,
          country: null,
          twitch: null,
        },
      ],
      won: false,
    },
    {
      players: [
        {
          race: 0,
          rndRace: null,
          oldMmr: 2140,
          currentMmr: 0,
          battleTag: "StarBuck#2732",
          name: "StarBuck",
          mmrGain: -2140,
          won: false,
          location: "SI",
          countryCode: "SI",
          country: null,
          twitch: "starbuck",
        },
        {
          race: 2,
          rndRace: null,
          oldMmr: 2073,
          currentMmr: 0,
          battleTag: "ic3#21532",
          name: "ic3",
          mmrGain: -2073,
          won: false,
          location: "DE",
          countryCode: null,
          country: null,
          twitch: null,
        },
        {
          race: 0,
          rndRace: null,
          oldMmr: 1995,
          currentMmr: 0,
          battleTag: "lmao#21922",
          name: "lmao",
          mmrGain: -1995,
          won: false,
          location: "NL",
          countryCode: "HM",
          country: null,
          twitch: "",
        },
        {
          race: 0,
          rndRace: null,
          oldMmr: 1738,
          currentMmr: 0,
          battleTag: "Signspree#2824",
          name: "Signspree",
          mmrGain: -1738,
          won: false,
          location: "CZ",
          countryCode: null,
          country: null,
          twitch: null,
        },
      ],
      won: false,
    },
  ],
  gateWay: 20,
  season: 0,
  number: null,
  serverInfo: { provider: "BNET", nodeId: null, countryCode: null, location: null, name: null, playerServerInfos: [] },
};

export default fakeData;
